# Generated by Django 3.1.4 on 2021-04-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='news_id',
            new_name='posts_id',
        ),
    ]
