# Generated by Django 3.1.4 on 2021-01-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210117_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='imgurl',
            field=models.TextField(default='-'),
        ),
    ]
