# Generated by Django 3.1.4 on 2021-01-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_posts_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='ocatid',
            field=models.IntegerField(default=0),
        ),
    ]
