# Generated by Django 3.1.4 on 2021-01-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210121_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='tag',
            field=models.TextField(default=''),
        ),
    ]
