# Generated by Django 3.1.4 on 2021-04-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_posts_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='act',
            field=models.IntegerField(default=0),
        ),
    ]
