# Generated by Django 3.1.4 on 2021-04-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_posts_act'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='rand',
            field=models.IntegerField(default=0),
        ),
    ]
