# Generated by Django 3.1.4 on 2021-01-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210114_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='logoname',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='main',
            name='logourl',
            field=models.TextField(default=''),
        ),
    ]
