# Generated by Django 3.1.4 on 2021-01-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210124_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='logoname2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='main',
            name='logourl2',
            field=models.TextField(default=''),
        ),
    ]
