# Generated by Django 3.1.4 on 2021-01-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210124_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='abouttext',
            field=models.TextField(default=''),
        ),
    ]
